services:
  postgres:
    image: postgres:17.5
    container_name: db_evolution_api
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db_evolution_api
    ports:
      - "5432:5432"
    volumes:
      - .volumes/db_evolution_api:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_evolution_api
    restart: always
    ports:
      - "6379:6379"

  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - evolution_instances:/evolution/instances

volumes:
  postgres_data:
  evolution_instances: